### ISSUE TITLE
报错 CANNOT LINK EXECUTABLE "./zerotier-one": cannot locate symbol "_Unwind_Resume" referenced by "/data/adb/zerotier/zerotier-one"

### ISSUE THREAD

**Issue by yu1chaofan** [eventlOwOp/zerotier-magisk#1]
![image](https://github.com/eventlOwOp/zerotier-magisk/assets/32660987/2f42003c-dee2-4869-8bff-5cfba2c56839)

![image](https://github.com/eventlOwOp/zerotier-magisk/assets/32660987/40a6834c-b62b-476c-a7b7-7ae7938ae9b9)

**Comment by yu1chaofan** [comment]
还有一台手机也报错啦
![image](https://github.com/eventlOwOp/zerotier-magisk/assets/32660987/f2540dc0-a013-4c54-b64f-e0fa789233f5)

![image](https://github.com/eventlOwOp/zerotier-magisk/assets/32660987/318b6c3b-1343-4db2-b702-b70305946e58)

**Comment by yu1chaofan** [comment]
mi10s使用的没问题

**Comment by eventlOwOp** [comment]
https://blog.csdn.net/gunwithrose/article/details/1922741
我照着这个编译一下，你再试试

**Comment by eventlOwOp** [comment]
不是上面那个问题，我觉得就是库不一样，我把所有我的库复制出来得了

**Comment by eventlOwOp** [comment]
加了4个库，你再试试

**Comment by yu1chaofan** [comment]
![image](https://github.com/eventlOwOp/zerotier-magisk/assets/32660987/8f7e628e-6e71-4fe9-850a-7e26534c3904)
还是报错啦
我尝试编译过,整不明白啊

**Comment by eventlOwOp** [comment]
这个是warning，可以尝试不用管他；
自己编译可以用我刚传到zerotier这个branch的压缩文件去编译，需要改的我都改好了，安装termux编译即可
编译提示缺少啥装啥就行了

**Comment by yu1chaofan** [comment]
好的,是不是需要在不能运行的设备上面编译

**Comment by eventlOwOp** [comment]
yes

**Comment by yu1chaofan** [comment]
卧槽,大佬可以了!!!!!!

**Comment by eventlOwOp** [comment]
好好好，晚上我又没写作业

**Comment by eventlOwOp** [comment]
如果你愿意可以开个pr传一下你的build，只用传zerotier-one

**Comment by yu1chaofan** [comment]
我还不是很会git,我取找一下教程,再传一个

**Comment by yu1chaofan** [comment]
提交pr了,也不知道对不对

**Comment by eventlOwOp** [comment]
谢谢你的贡献💖

**Comment by eventlOwOp** [comment]
你可以更新再试试；当然先备份好能用的版本（）
