### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by StarClound** [eventlOwOp/zerotier-magisk#10]
连不上，不知道哪里出问题了，看不懂log(

**Comment by StarClound** [comment]
设备:红米k20p
安卓版本:9
MIUI10 9.8.1
zerotier.log

1:1 UTF-8

ПD/ПD.SU unuseu DT enuy. unKПUWI

processor-specific (type 0x70000001 arg2,0xO) (ignoring)

28 WARNING: linker: Warning: "/data/ adb/ zerotier/s ,lib/libdl.so" unused DT entry: unknown

processor-specific (type 0x70000001 arg?,OxО) (ignoring)

29 WARNING: linker: Warning: "/data/adb/ zerotier/,,lib/libc. so" unused DT entry: unknown

processor-specific (type 0x70000001 argi,Ox0) (ignoring)

30 WARNING: linker: Warning: "/data/adb/ zerotier/,lib/libc.so" unused DT entry; unknown

processor-specific (type 0x 70000001 arg,,0x0) (ignoring)

31 WARNING: linker: Warning; "/data/ adb/ zerotier/lib/ libdl.so" unused DT entry: unknown

processor-specific (type 0x70000001 arg7,OxO) (ignoring)

32 WARNING: linker: Warning: "/data/ adb/ zerotier/,,lib/libc, so" unused DT entry: unknown

processor-specific (type 0x70000001 arg2OxO) (ignoring)

33 WARNING: linker: Warning: "/data/ adb/ zerotier/,,lib/libdl.so" unused DT entry; unknown

processor-specific (type Ox 70000001 arg,,0x0) (ignoring)

34 CANNOT LINK EXECUTABLE "/data/adb/zerotier/zerotier-one": cannot locate symbol_loader_ shared, globals" referenced by "/7,data/ adb/ zerotier/lib/libc.so"..

**Comment by eventlOwOp** [comment]
换gcc版本应该是可以用的
ndk我要再修一下
ld查找路径不太对

**Comment by eventlOwOp** [comment]
ld_library_path改了，要重新编译，app也要编译，可能得等下一个大版本了（懒）
反正gcc版本可以用的，先用gcc吧

**Comment by eventlOwOp** [comment]
gcc不能用再来cue我

**Comment by StarClound** [comment]
之前试了gcc也用不了，不过忘了啥报错了，就一直想有个zerotier模块用，一直在看这里面有没有能借鉴的办法，其他两个模块也看了好像不是很好用，一个是ksu的，另一个刷不进去(悲)。然后今天折腾了半天终于整明白了，去/data/adb/zerotier/lib/删掉除了libc++_shared.so以外的四个文件就好了!一点也没报错，给我整不会了，还是看了看之前那位大哥发的note7那个issue，想着怎么办呢，突然通了(

**Comment by StarClound** [comment]
/data/adb/zerotier/lib/里面是有五个.so文件的，就留一个libc++_shared.so就一点不报错了

**Comment by StarClound** [comment]
但是我的另一台手机 安卓11 colors11的机子刷了就正常，/data/adb/zerotier/lib/里面也只有一个libc++_shared.so

**Comment by eventlOwOp** [comment]
你从release下的任何东西lib里面都只有一个libc++_shared.so啊
是从老版本更新上来的是吧🤔
那我还得去适配一下更新

**Comment by eventlOwOp** [comment]
gcc用不了还真有可能就是kernel版本太低，link到了什么没有的syscall

这个问题用ndk确实可以解决，老版本我当时没翻ndk文档，现在翻了我知道只需要libc++_shared.so一个库了。加上其他的还容易出问题

不过安装脚本没有考虑从老版本更新的问题🤔

我再去build一个ndk的你从release下载安装吧，应该能用了

**Comment by StarClound** [comment]
刚好下课，回宿舍马上刷:)
