### ISSUE TITLE
大佬help

### ISSUE THREAD

**Issue by StarClound** [eventlOwOp/zerotier-magisk#11]
刷了最新版的之后，那些sh文件都消失了，除了zerotier.sh还在 ，然后没反应了，然后我又作死刷了另外两台试试，另外两台也gg了，刷回老版本也不行，很老的老版本有start.sh，但是启动发现端口被占用
这是zerotier.log
WARNING: linker: Warning: "/data/adb/zerotier/lib/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
Starting Control Plane...
Starting V6 Control Plane...
救救孩子😭

**Comment by StarClound** [comment]
模块全部删了，重新安装模块app
app network界面显示
Error: ProcessException: No such file or directory
Command: su -C cat /data/adb/zerotier/home/authtoken. secret
😭

**Comment by eventlOwOp** [comment]
?

**Comment by eventlOwOp** [comment]
我自己试了一下可以用的

**Comment by eventlOwOp** [comment]
app出问题是su授权授权不起，你可能隐藏了还是怎么样

**Comment by StarClound** [comment]
是因为面具被系统杀了😭

**Comment by StarClound** [comment]
已经搞定了 谢谢大佬😊

**Comment by eventlOwOp** [comment]
卑微开发者在线求star
