### ISSUE TITLE
Cannot connect to the online device with zerotier magisk

### ISSUE THREAD

**Issue by ifloppy** [eventlOwOp/zerotier-magisk#15]
你好，请教一下。我在一台安卓手机上安装了zerotier-magisk，并成功连接到我的网络，在my.zerotier.com上可以看到设备一直处于在线状态。但是过一段时间后，我无法通过ZeroTier ping通或访问这台设备上的SSH和Web服务器，尽管设备仍显示在线。我可以通过这台设备上运行的frp服务访问Web服务器，这证明服务器正常工作。通过App重启ZeroTier可以暂时解决这个问题，但过一段时间后问题又会出现。

Translated:

Hello, I need some help. I installed zerotier-magisk on an Android phone and successfully connected it to my network. The device consistently shows as online on my.zerotier.com. However, after some time, I am unable to ping or access the SSH and web server on this device through ZeroTier, even though it still shows as online. I can access the web server via the frp service running on this device, which proves the server is working fine. Restarting ZeroTier through the app temporarily resolves the issue, but it reoccurs after a while.

**Comment by eventlOwOp** [comment]
有移动数据和wifi的切换啥的吗，或者息屏的断网啥的。如果有确实是不好解决的问题，如果没有应该不会断连呢🥺

主要是zerotier本来也对这种频繁变化的网络环境支持的很差😭

倒是可以尝试每次息屏亮屏重启zerotier，但是会很耗电

**Comment by eventlOwOp** [comment]
其实我使用中zerotier也会自动重连，只是速度会比较慢（

比如息屏/切换网络后要等很久才能ping通啥的

**Comment by ifloppy** [comment]
> 有移动数据和wifi的切换啥的吗，或者息屏的断网啥的。如果有确实是不好解决的问题，如果没有应该不会断连呢🥺
> 
> 主要是zerotier本来也对这种频繁变化的网络环境支持的很差😭
> 
> 倒是可以尝试每次息屏亮屏重启zerotier，但是会很耗电

谢谢您的回答。

这台设备是放在固定的地方当作家用服务器使用的，使用DozeOff锁定了使用Wifi的，不应该出现网络切换的情况。所以我不理解为什么会出现这个问题。

刚刚看了一下，突然又可以连上了，但是我没有对这台手机进行任何操作。这很奇怪。
