### ISSUE TITLE
使用流量上网的情况下经常断网

### ISSUE THREAD

**Issue by powerAn2020** [eventlOwOp/zerotier-magisk#4]
如题，你们有遇到在用流量上网时只有上传没有下载的问题吗，而且出现时机不固定，但是物理位置没有发生变化。这应该不是基站的问题。关闭模块并重启手机后，就可以正常上网了。

**Comment by eventlOwOp** [comment]
zerotier默认是修改main这个路由表，但是android默认不去lookup这个表。模块开机时用ip rule把查这个表的规则加进去了，优先级比流量/wifi上网的高。所以你可以看看你zerotier设置的路由表。如果你zerotier的路由表允许所有流量经过，而不是只允许虚拟局域网网段的流量经过的话，就会上不了网。如果只让虚拟局域网网段经过，无论zerotier服务出现什么问题，只有访问局域网受影响，上网是不会受影响的。
一般组虚拟局域网的使用是不会让所有流量经过zerotier的，如果你是做代理使用那本模块不支持这样的使用方法。
改改插入ip rule的优先级可能可以解决

**Comment by powerAn2020** [comment]
@eventlOwOp 如果说真的允许所有流量通过的话，网络为什么一阵一阵的，而且在连WiFi情况下基本是没发现问题，只有在流量的时候会出现，一段时间不管它，现象可能就又会有所好转，但是过不了多久就又上不了网了😅以下是我的路由配置信息，![image](https://github.com/eventlOwOp/zerotier-magisk/assets/25736019/e59da55a-6753-4f8e-a9a6-a3a89919cf0d)

**Comment by eventlOwOp** [comment]
1. 有可能你的172这个网段和你流量上网所使用的网段冲突了，可以使用ifconfig看rmnet开头网卡的inet addr看到你流量上网使用的网段。
2. 你可以使用ip route，找出里面使用zt*开头的网卡的路由，这样就知道哪些流量经过zerotier，如果你的其他流量不经过zerotier，多半不是本模块导致的问题。如果是，我无法复现也就无法解决，如果你能自行解决欢迎你提供解决方案。

**Comment by eventlOwOp** [comment]
我重新编译了一下，之前的好像被覆盖成了kernel=4.14下的编译。你可以从master branch下载一下再试试。不保证有用。

**Comment by eventlOwOp** [comment]
不知道捏

**Comment by powerAn2020** [comment]
真的好奇怪，不晓得咋排查，我之前试过自己编译arm版本，然后在路由表id 254/255添加路由，但是也是相同的问题😢

**Comment by eventlOwOp** [comment]
你用的是主流品牌的设备吗? android版本和kernel版本够新吗? 我猜测可能是更底层的问题。

**Comment by powerAn2020** [comment]
redmi k40,自编译的内核,miui14

**Comment by powerAn2020** [comment]
应该是系统问题，看了下小米社区，k40这个版本反馈信号有问题的人很多。

**Comment by powerAn2020** [comment]
发现问题，断网的时候出现这个了
sendto: Operation not permitted
