### ISSUE TITLE
missing port and zerotier-one.port not found in /var/lib/zerotier-one

### ISSUE THREAD

**Issue by chenyurumeng** [eventlOwOp/zerotier-magisk#6]
大佬您好，模块很好，访问内网正常，但是无法命令查看，提示报错如下，如何解决，谢谢！
sdcard su -c
# sdcard cd /data/adb/zerotier/
# zerotier ./zerotier-cli listnetworks
./zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
# zerotier

**Comment by eventlOwOp** [comment]
你可以去翻翻zerotier目录下其他sh的写法
使用cli可执行文件要加-D./home这个

**Comment by chenyurumeng** [comment]
感谢，按照你说的解决了

**Comment by eventlOwOp** [comment]
更新了，现在可以直接用了（）
