### ISSUE TITLE
Sometimes the zero network fails after switching wifi---有时切换wifi后zero网络故障

### ISSUE THREAD

**Issue by ddns6** [eventlOwOp/zerotier-magisk#7]
![240418](https://github.com/eventlOwOp/zerotier-magisk/assets/100478073/e724232f-85c0-454f-a317-e80c0ca3f9b9)
The details are shown in the figure below, which is restored after restarting the service.

I recommend optimizing service.sh:
1. Boot delay start: 10 seconds.
2. Join WLAN monitoring: 30 seconds at a loop interval, and automatically restart the service when v4 or v6 changes.

-----------------------------------------------------
详情如下图，重启服务后恢复。

本人建议优化service.sh：
1，开机延时启动：10秒。
2，加入WLAN监听：循环间隔30秒，当v4或v6发生变动时，自动重启服务。

**Comment by ddns6** [comment]
C:\Users\zjq13>adb shell
mondrian:/ $ su

mondrian:/ # ping 10.2.2.9
PING 10.2.2.9 (10.2.2.9) 56(84) bytes of data.
From 10.2.2.6: icmp_seq=10 Destination Host Unreachable
From 10.2.2.6: icmp_seq=11 Destination Host Unreachable

mondrian:/ # ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=53 time=233 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=53 time=245 ms

2|mondrian:/ # killall -9 zerotier-one
2|mondrian:/ # sh /data/adb/modules/zerotier/service.sh
RTNETLINK answers: File exists
0 join connection failed
123|mondrian:/ # Starting Control Plane...
Starting V6 Control Plane...

2|mondrian:/ # ping 10.2.2.9
PING 10.2.2.9 (10.2.2.9) 56(84) bytes of data.
64 bytes from 10.2.2.9: icmp_seq=1 ttl=64 time=1820 ms
64 bytes from 10.2.2.9: icmp_seq=2 ttl=64 time=1337 ms

**Comment by eventlOwOp** [comment]
android监控wifi连接目前我没太找到什么解决方案，可能需要配套android app实现，shell可能不太会去更新，后续还是考虑写android app去控制
可以试一下其他的仓库 https://github.com/linuxscreen/ZeroTierOneForMagisk

**Comment by ddns6** [comment]
给看看有没有啥大问题？
#!/system/bin/sh
MODDIR=${0%/*}

cd /data/adb/zerotier/

sleep 10
sh ./start.sh
sleep 5
sh ./join.sh
sh ./add_ip_rule.sh
while [ "$(getprop sys.boot_completed)" != "1" ]; do
        sleep 1
    done
echo "PowerManagerService.noSuspend" > /sys/power/wake_lock

while true;
do
 v4=$(curl -s http://ipv4.icanhazip.com)
 v6=$(curl -s http://ipv6.icanhazip.com)
 v4log="/data/adb/zerotier/v4log.txt"
 v6log="/data/adb/zerotier/v6log.txt"
#无网休60秒.有网未变休300秒.否则记录ip并重启
if [ "$(ping -c 1 223.5.5.5 | wc -l)" = "0" ];then
  echo "无网络将在60秒后重试"
  kill -9 $(pgrep zerotier)
elif [[ "$v4" = "$(cat "$v4log")" && "$v6" = "$(cat "$v6log")" ]];then
  echo "ip无变化.将在300秒后重新比对"
  sleep 240
else
  echo "ip更新重启中"
  echo "$v4" > "$v4log"
  echo "$v6" > "$v6log"
  kill -9 $(pgrep zerotier)
  sleep 2
  sh ./start.sh
  sleep 5
  sh ./join.sh
  sh ./add_ip_rule.sh
fi
sleep 60
done

**Comment by ddns6** [comment]
> android监控wifi连接目前我没太找到什么解决方案，可能需要配套android app实现，shell可能不太会去更新，后续还是考虑写Android app去控制 可以试一下其他的仓库 https://github.com/linuxscreen/ZeroTierOneForMagisk

去试了一下这个模块，直接不能安装，最后还得回来用你这个：
![Screenshot_2024-04-20-14-48-12-062_a yikpqzy](https://github.com/eventlOwOp/zerotier-magisk/assets/100478073/6064ded8-235f-4f6f-b26d-3353c4d3aab5)

**Comment by powerAn2020** [comment]
@ddns6 感觉这个是zerotier的锅，我编译的也是一样的问题，有一次手动启动进程的时候，网络故障的出现了报错，`sendto: Operation not permitted`。然后就是断网了，只能重启进程解决。

**Comment by eventlOwOp** [comment]
我本机测试切换wifi zerotier一般不会出问题
如果出问题也是zerotier的问题，感觉挂个监控区监控zerotier的状态过于损失性能，解决方案应该还是弄个app去控制zerotier的启动和重启

**Comment by powerAn2020** [comment]
我切换Wi-Fi复现率也非常低。但是在流量模式下复现率挺高的，尤其是在周围基站数多的情况下，（4g/5g切换频繁复现率更高，我现在只能关闭5g使用。）个人认为弄个app，感觉和脚本没什么区别，甚至比脚本还占用资源吧，毕竟还隔着一个虚拟机呢，最好的方法还是找到为什么报错，然后在zerotier源码里改代码，退而求其次也是在zerotier源码里做网络监听吧。当然了，不会写c/c++的菜鸡表示对此无能为力。。。🤣

**Comment by ddns6** [comment]
原来还有人在关注这个问题，贴上我的service，虽然不知道它有没有严重bug，但还是贡献出来，大家自行测试、后果自行承担。如果有大佬的话请帮忙改改（目前未对service提权）

#!/system/bin/sh
MODDIR=${0%/*}
cd /data/adb/zerotier/
sleep 10
sh ./start.sh
sleep 5
sh ./join.sh
sh ./add_ip_rule.sh
while [ "$(getprop sys.boot_completed)" != "1" ]; do
        sleep 1
    done
echo "PowerManagerService.noSuspend" > /sys/power/wake_lock

while true;
do
 v4=$(curl -s http://ipv4.icanhazip.com)
 v6=$(curl -s http://ipv6.icanhazip.com)
 v4log="/data/adb/zerotier/v4log.txt"
 v6log="/data/adb/zerotier/v6log.txt"
#无网休60秒.有网未变休300秒.否则记录ip并重启
if [ "$(ping -c 1 223.5.5.5 | wc -l)" = "0" ];then
  echo "无网络将在60秒后重试"
  kill -9 $(pgrep zerotier)
elif [[ "$v4" = "$(cat "$v4log")" && "$v6" = "$(cat "$v6log")" ]];then
  echo "ip无变化.将在300秒后重新比对"
  sleep 240
else
  echo "ip更新重启中"
  echo "$v4" > "$v4log"
  echo "$v6" > "$v6log"
  kill -9 $(pgrep zerotier)
  sleep 2
  sh ./start.sh
  sleep 5
  sh ./join.sh
  sh ./add_ip_rule.sh
fi
sleep 60
done

**Comment by eventlOwOp** [comment]
> 我切换Wi-Fi复现率也非常低。但是在流量模式下复现率挺高的，尤其是在周围基站数多的情况下，（4g/5g切换频繁复现率更高，我现在只能关闭5g使用。）个人认为弄个app，感觉和脚本没什么区别，甚至比脚本还占用资源吧，毕竟还隔着一个虚拟机呢，最好的方法还是找到为什么报错，然后在zerotier源码里改代码，退而求其次也是在zerotier源码里做网络监听吧。当然了，不会写c/c++的菜鸡表示对此无能为力。。。🤣

我的意思是弄一个用来设置network id以及启动关闭重启的app，后台监控感觉确实浪费资源太多
但是要等放假写了

**Comment by powerAn2020** [comment]
> 原来还有人在关注这个问题，贴上我的service，虽然不知道它有没有严重bug，但还是贡献出来，大家自行测试、后果自行承担。如果有大佬的话请帮忙改改（目前未对service提权）
> 
> #!/system/bin/sh MODDIR=${0%/*} cd /data/adb/zerotier/ sleep 10 sh ./start.sh sleep 5 sh ./join.sh sh ./add_ip_rule.sh while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 1 done echo "PowerManagerService.noSuspend" > /sys/power/wake_lock
> 
> while true; do v4=$(curl -s http://ipv4.icanhazip.com) v6=$(curl -s http://ipv6.icanhazip.com) v4log="/data/adb/zerotier/v4log.txt" v6log="/data/adb/zerotier/v6log.txt" #无网休60秒.有网未变休300秒.否则记录ip并重启 if [ "$(ping -c 1 223.5.5.5 | wc -l)" = "0" ];then echo "无网络将在60秒后重试" kill -9 $(pgrep zerotier) elif [[ "$v4" = "$(cat "$v4log")" && "$v6" = "$(cat "$v6log")" ]];then echo "ip无变化.将在300秒后重新比对" sleep 240 else echo "ip更新重启中" echo "$v4" > "$v4log" echo "$v6" > "$v6log" kill -9 $(pgrep zerotier) sleep 2 sh ./start.sh sleep 5 sh ./join.sh sh ./add_ip_rule.sh fi sleep 60 done

个人觉得，频繁的网络请求来确定网络是否变动不太靠谱，浪费电不说还浪费流量（虽然流量都很多不差这点），而且像MIUI这种夜间还断网的。。。。建议直接`ip addr` 保存排序然后每次用`grep `判定文件是否有差异，有就重启，没有就跳过。

**Comment by eventlOwOp** [comment]
https://github.com/zerotier/ZeroTierOne/issues/1549

zt自己的问题吧

**Comment by powerAn2020** [comment]
@eventlOwOp @ddns6 试试最新版，我来回断开Wi-Fi，切换数据暂时还没复现过。
-- 
# 2024-05-02 -- Version 1.14.0

  * Linux I/O performance improvements under heavy load
  * Improvements to multipath
  * Fix for port rebinding "coma" bug after periods offline (some laptop users)
  * Fixed a rules engine quirk/ambiguity (GitHub Issue #2200)
  * Controller API enhancements: node names and other node meta-data
  * Other bug fixes

**Comment by eventlOwOp** [comment]
> ## @eventlOwOp @ddns6 试试最新版，我来回断开Wi-Fi，切换数据暂时还没复现过。
> # 2024-05-02 -- Version 1.14.0
> * Linux I/O performance improvements under heavy load
> * Improvements to multipath
> * Fix for port rebinding "coma" bug after periods offline (some laptop users)
> * Fixed a rules engine quirk/ambiguity (GitHub Issue #2200)
> * Controller API enhancements: node names and other node meta-data
> * Other bug fixes

来了，release里面直接装，network id的配置路径改了一下

**Comment by eventlOwOp** [comment]
@powerAn2020

**Comment by powerAn2020** [comment]
> 我本机测试切换wifi zerotier一般不会出问题 如果出问题也是zerotier的问题，感觉挂个监控区监控zerotier的状态过于损失性能，解决方案应该还是弄个app去控制zerotier的启动和重启

KSU下我已经做了UI。 @eventlOwOp

**Comment by eventlOwOp** [comment]
Android APP 做好了，一键重启，避免后台监控耗电。

同时更新到 v1.14.0 后不易断开了

还有 NDK GCC 多种版本供君选择
